/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menu;

import Logic.Produto;
import Logic.Produtos;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author danie
 */
public class TelaADD extends javax.swing.JInternalFrame {
    
    private Color color;
    private static TelaADD telaADD;
    public static TelaADD getInstancia(){
        if(telaADD == null || telaADD.isClosed() || !telaADD.isDisplayable()){
            telaADD = new TelaADD();
            telaADD.setLocation(0,0);
        } 
        return telaADD;
        
    }
    
    
    
    /**
     * Creates new form TelaADD
     */
    public TelaADD() {
        initComponents();
        
        iniciarCategorias();
    }
    
    private void iniciarCategorias(){
        
        File file = new File("save/dadosCategorias.ser");

        // Verifica se o arquivo existe antes de tentar lê-lo
        if (!file.exists()) {
            String[] c = {"Camiseta", "Boné", "Caneca", "Xícara"};

            for (int i = 0; i < c.length; i++) {
                Produtos.addCategoria(c[i]);
                adicionarItemSeNaoExistir(c[i]);
            }
            combobox1.setSelectedIndex(-1);
            return;
        }
        try (FileInputStream fileIn = new FileInputStream("save/dadosCategorias.ser"); ObjectInputStream objectIn = new ObjectInputStream(fileIn)) {
            ArrayList<String> nCategorias = (ArrayList<String>) objectIn.readObject();
            Produtos.setCategorias(nCategorias);
            
            for(String cat : Produtos.getCategorias()){
                
                adicionarItemSeNaoExistir(cat);
            }
            combobox1.setSelectedIndex(-1);
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        
        
    }

    public void adicionarItemSeNaoExistir(String novoItem) {
        // Converte o novo item para minúsculas para a comparação ignorar maiúsculas e minúsculas
        String novoItemMinusc = novoItem.toLowerCase();

        boolean itemExiste = false;
        for (int i = 0; i < combobox1.getItemCount(); i++) {
            String itemExistente;
            itemExistente = (String) combobox1.getItemAt(i);
            itemExistente = itemExistente.toLowerCase();
            if (itemExistente.equals(novoItemMinusc)) {
                itemExiste = true;
                break;
            }
        }

        if (!itemExiste) {
            combobox1.addItem(novoItem);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        textField8 = new Menu.TextField();
        textField9 = new Menu.TextField();
        textField10 = new Menu.TextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        combobox1 = new Menu.Combobox();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("Excluir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setTitle("Novo Produto");

        jButton1.setBackground(new java.awt.Color(115, 197, 141));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salvar");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textField8.setBackground(new java.awt.Color(51, 51, 51));
        textField8.setForeground(new java.awt.Color(255, 255, 255));
        textField8.setLabelText("Descrição");
        textField8.setName(""); // NOI18N

        textField9.setBackground(new java.awt.Color(51, 51, 51));
        textField9.setForeground(new java.awt.Color(255, 255, 255));
        textField9.setLabelText("Quantidade");

        textField10.setBackground(new java.awt.Color(51, 51, 51));
        textField10.setForeground(new java.awt.Color(255, 255, 255));
        textField10.setLabelText("Preco");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Select");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.white));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        combobox1.setSelectedIndex(-1);
        combobox1.setLabeText("Categoria");
        combobox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox1MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(textField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        textField8.getAccessibleContext().setAccessibleName("");
        textField10.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        color = color.BLACK;
        color = JColorChooser.showDialog(this,"Selecione uma cor",color);
        
        if(color == null){
            color = color.WHITE;
        }
        jPanel1.setBackground(color);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String textoPreco = textField10.getText();
            textoPreco = textoPreco.replace(',', '.');
            int quantidade = Integer.parseInt(textField9.getText());
            double preco = Double.parseDouble(textoPreco);
            int id = Produtos.getCount();
            
            Object[] produtosT = {id,combobox1.getSelectedItem(),textField8.getText(),quantidade,preco,color};
            TelaProdutos.getInstancia().atualizaTabela(produtosT);
            Produtos.addProduto(new Produto(id,(String) combobox1.getSelectedItem(),textField8.getText(),quantidade,preco,color));
            
            telaADD.dispose();
        }catch (NumberFormatException e) {
            // Trate o erro, como mostrar uma mensagem de erro ao usuário
            System.out.println("Entrada inválida, por favor insira um número inteiro.");
            JOptionPane.showMessageDialog(null, "Numero Invalido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String novaCategoria = JOptionPane.showInputDialog(this, "Nome da Categoria:");
        if (novaCategoria != null && !novaCategoria.isEmpty()) {
            adicionarItemSeNaoExistir(novaCategoria);
            Produtos.addCategoria(novaCategoria);
            Produtos.SalvarCategorias(); // Atualiza o arquivo após a adição
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void combobox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox1MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            jPopupMenu1.show(combobox1, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_combobox1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (combobox1.getSelectedItem() != null) {
            Object ItemRemoved = combobox1.getSelectedItem();
            combobox1.removeItem(ItemRemoved);
            Produtos.removeCategoria((String) ItemRemoved);
            
            Produtos.SalvarCategorias();// Atualiza o arquivo após a remoção
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Menu.Combobox combobox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private Menu.TextField textField10;
    private Menu.TextField textField8;
    private Menu.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
